export const HEADER_TOOLSET_OPTIONS = {
    BOLD: 'BOLD',
    ITALIC: 'ITALIC',
    UNDERLINE: 'UNDERLINE',
    HEADINGONE: 'HEADINGONE',
    HEADINGTWO: 'HEADINGTWO',
    HEADINGTHREE: 'HEADINGTHREE'
}